apiVersion: v2
name: fastapiapp
description: A Helm chart for FastAPI microservices
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami

